### ISSUE TITLE
all records to be same only the key different

### ISSUE THREAD

**Issue by fs-wu** [tkrs/embulk-output-aerospike#3]
I use sql for input and aerospike as output, after run embulk, I found all the values in aerospike became the last one record from sql select and only the PK different.
For example, 
the data in db table as : 

| user_id | user_no | status |
| --- | --- | --- |
| 0000000000609692 | 1 | ng |
| 0000000000609777 | 2 | ng |
| 0000000000609787 | 3 | ok |

and the embulk config like:

```
in:
  type: mysql
  host: localhost
  user: root
  password: root
  database: test
  query: "select user_id, user_no, customer_status as status from users limit 3"
out:
  type: aerospike
  hosts:
  - {name: '127.0.0.1', port: 3000}
  command: put
  namespace: bar
  set_name: users
  key_name: user_id
  write_policy:
    send_key: true
```

and I will get result like:

| key | user_no | status |
| --- | --- | --- |
| 0000000000609692 | 3 | ok |
| 0000000000609777 | 3 | ok |
| 0000000000609787 | 3 | ok |

the debug log show that after toRecords method, the rec.toMap like such as:

```
Map(user_no -> 3, status -> ok, user_id -> 0000000000609787)
```

Is createRecords wrong?
